import { getSession } from "@/lib/session";
import "@/styles/globals.css";
import { type Metadata } from "next";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const session = getSession()
  // console.log(session)
  return (
    <div className=" w-full flex flex-row h-screen  bg-gray-500 bg-[url('/bg.jpg')] bg-cover">
        {/* <div className=" hidden md:flex flex-1">
        </div> */}
        <div className=" flex-1 flex items-center justify-center bg-black bg-opacity-50">
        {children}
        </div>
    </div>
  );
}
