import { ModeToggle } from "@/app/_components/theme-mode";
import "@/styles/globals.css";
import { type Metadata } from "next";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className=" w-full flex flex-row h-screen  bg-[url('/bg.jpg')] bg-cover relative">
      <div className=" absolute top-5 left-5">

      <ModeToggle/>
      </div>
        {/* <div className=" hidden md:flex flex-1">
        </div> */}
        {children}
    </div>
  );
}
